project:
  type: website

website:
  title: "Machine Learning"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rahulpulluri/MLBlog
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual